<item>
   <title>Issue #1912 created</title>
   <pubDate>2025-04-04T14:05:19Z</pubDate>
   <link>https://github.com/qt4cg/qtspecs/issues/1912</link>
   <guid>https://qt4cg.org/@qt4cg/2025/#created-1912</guid>
   <description>&lt;div&gt;&lt;p&gt;Error handling: `fn:throw`&lt;/p&gt;&lt;div class="markup"&gt;&lt;p&gt;Adopted from #501:&lt;/p&gt;
&lt;p&gt;In https://github.com/qt4cg/qtspecs/pull/493, a function/expression was suggested to re-throw errors:&lt;/p&gt;
&lt;pre&gt;&lt;code class="language-xquery"&gt;try {
  (: wild stuff :)
} catch * {
  module:log($err:description),
  fn:throw($err:map)
}
&lt;/code&gt;&lt;/pre&gt;
&lt;p&gt;Existing errors map can be modified before rethrowing them:&lt;/p&gt;
&lt;pre&gt;&lt;code class="language-xquery"&gt;try {
  1 div 0
} catch * {
  module:log($err:description),
  fn:throw($err:map =&amp;gt; map:put('description', 'Arithmetic error'))
}
&lt;/code&gt;&lt;/pre&gt;
&lt;/div&gt;&lt;/div&gt;</description>
</item>
